### ISSUE TITLE
Fix coverage and improve test suite

### ISSUE THREAD

**Issue by joostverdoorn** [joostverdoorn/sonic#6]
- [ ] `src/sonic.coffee`
- [ ] `src/signal.coffee`
- [ ] `src/iterator.coffee`
- [ ] `src/abstract_list.coffee`
- [ ] `src/list.coffee`
- [ ] `src/unit.coffee`
- [ ] `src/flat_map_list.coffee`
- [ ] `src/group_list.coffee`
- [ ] `src/take_list.coffee`

**Comment by steffansluis** [comment]
There is a branch for this now! The aptly named `tests`-branch.
